name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies 
        # Use 'ci' instead of 'install' for a cleaner, faster, more reliable build
        run: npm ci  

      - name: Check style        
        # We call eslint via npm to avoid permission issues with the binary
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e